import { SETTINGS_KEYS, SETTINGS_DEFAULTS } from "@/constants/settings";

export const RECEIPT_SETTINGS_KEYS = {
  FOUNDATION_NAME: SETTINGS_KEYS.FOUNDATION_NAME,
  FOUNDATION_ADDRESS: SETTINGS_KEYS.FOUNDATION_ADDRESS,
  FOUNDATION_PHONE: SETTINGS_KEYS.FOUNDATION_PHONE,
  BANK_NAME: SETTINGS_KEYS.BANK_NAME,
  BANK_ACCOUNT_NUMBER: SETTINGS_KEYS.BANK_ACCOUNT_NUMBER,
  BANK_ACCOUNT_NAME: SETTINGS_KEYS.BANK_ACCOUNT_NAME,
  FOOTER_MESSAGE: SETTINGS_KEYS.RECEIPT_FOOTER_MESSAGE,
  SIGNATURE_NAME: SETTINGS_KEYS.RECEIPT_SIGNATURE_NAME,
  SIGNATURE_POSITION: SETTINGS_KEYS.RECEIPT_SIGNATURE_POSITION,
} as const;

export const RECEIPT_SETTINGS_DEFAULTS = {
  [RECEIPT_SETTINGS_KEYS.FOUNDATION_NAME]: SETTINGS_DEFAULTS[SETTINGS_KEYS.FOUNDATION_NAME],
  [RECEIPT_SETTINGS_KEYS.FOUNDATION_ADDRESS]: SETTINGS_DEFAULTS[SETTINGS_KEYS.FOUNDATION_ADDRESS],
  [RECEIPT_SETTINGS_KEYS.FOUNDATION_PHONE]: SETTINGS_DEFAULTS[SETTINGS_KEYS.FOUNDATION_PHONE],
  [RECEIPT_SETTINGS_KEYS.BANK_NAME]: SETTINGS_DEFAULTS[SETTINGS_KEYS.BANK_NAME],
  [RECEIPT_SETTINGS_KEYS.BANK_ACCOUNT_NUMBER]: SETTINGS_DEFAULTS[SETTINGS_KEYS.BANK_ACCOUNT_NUMBER],
  [RECEIPT_SETTINGS_KEYS.BANK_ACCOUNT_NAME]: SETTINGS_DEFAULTS[SETTINGS_KEYS.BANK_ACCOUNT_NAME],
  [RECEIPT_SETTINGS_KEYS.FOOTER_MESSAGE]: SETTINGS_DEFAULTS[SETTINGS_KEYS.RECEIPT_FOOTER_MESSAGE],
  [RECEIPT_SETTINGS_KEYS.SIGNATURE_NAME]: SETTINGS_DEFAULTS[SETTINGS_KEYS.RECEIPT_SIGNATURE_NAME],
  [RECEIPT_SETTINGS_KEYS.SIGNATURE_POSITION]: SETTINGS_DEFAULTS[SETTINGS_KEYS.RECEIPT_SIGNATURE_POSITION],
} as const;

export const RECEIPT_ROUTES = {
  PREVIEW: (id: string) => `/dashboard/receipt/${id}`,
} as const;
